{
    "checksum": "4aa3da9c4b8030716dcd0ffcf97b53a226c76990567d4f99d8859e87de25b6ae",
    "file": "invalid-yaml-version.loader-error",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 19,
    "package": "pyyaml",
    "path": "pyyaml/6.0-1/tests/data/invalid-yaml-version.loader-error",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/pyyaml/6.0-1/",
        "metric": {
            "size": 3100
        },
        "pts_link": "https://tracker.debian.org/pkg/pyyaml",
        "sloc": [
            [
                "python",
                6941
            ],
            [
                "makefile",
                56
            ],
            [
                "ansic",
                8
            ],
            [
                "sh",
                8
            ]
        ],
        "suites": [
            "experimental"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/packages/pyyaml",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/pyyaml/6.0-1/tests/data/invalid-yaml-version.loader-error",
    "stat": {
        "perms": "rw-r--r--",
        "size": 20,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "6.0-1"
}