{
    "checksum": "21f1964eaa9b80bb85e7f265be1fde7363a972a09e9b8bbd1ada48e40853c515",
    "file": "no-resource-attributeerror-d0cb327abab7dcc0.yaml",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 3,
    "package": "python-ironicclient",
    "path": "python-ironicclient/4.8.0-2/releasenotes/notes/no-resource-attributeerror-d0cb327abab7dcc0.yaml",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-ironicclient/4.8.0-2/",
        "metric": {
            "size": 2292
        },
        "pts_link": "https://tracker.debian.org/pkg/python-ironicclient",
        "sloc": [
            [
                "python",
                23698
            ],
            [
                "makefile",
                20
            ],
            [
                "sh",
                16
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/openstack-team/clients/python-ironicclient",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-ironicclient/4.8.0-2/releasenotes/notes/no-resource-attributeerror-d0cb327abab7dcc0.yaml",
    "stat": {
        "perms": "rw-r--r--",
        "size": 415,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "4.8.0-2"
}