{
    "checksum": "ec791e6bf9e2a6a753008c1ac9033f6fab404beb30a6218b8b3d31fbf370c59a",
    "file": "SignedInvalidRFC822nameConstraintsTest22.eml",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 6,
    "package": "python-cryptography-vectors",
    "path": "python-cryptography-vectors/3.4.8-1/cryptography_vectors/x509/PKITS_data/smime/SignedInvalidRFC822nameConstraintsTest22.eml",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-cryptography-vectors/3.4.8-1/",
        "metric": {
            "size": 78852
        },
        "pts_link": "https://tracker.debian.org/pkg/python-cryptography-vectors",
        "sloc": [
            [
                "python",
                61
            ],
            [
                "sh",
                49
            ],
            [
                "makefile",
                3
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/packages/python-cryptography-vectors",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-cryptography-vectors/3.4.8-1/cryptography_vectors/x509/PKITS_data/smime/SignedInvalidRFC822nameConstraintsTest22.eml",
    "stat": {
        "perms": "rw-r--r--",
        "size": 5322,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "3.4.8-1"
}