{
    "checksum": "d186a60b0cbdeb9be5ade4602d912b310f8fd924ca31e14dba79aaf253023836",
    "file": "troubleshooting.md",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 1,
    "package": "python-fire",
    "path": "python-fire/0.4.0-1/docs/troubleshooting.md",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-fire/0.4.0-1/",
        "metric": {
            "size": 664
        },
        "pts_link": "https://tracker.debian.org/pkg/python-fire",
        "sloc": [
            [
                "python",
                6591
            ],
            [
                "makefile",
                9
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/packages/python-fire",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-fire/0.4.0-1/docs/troubleshooting.md",
    "stat": {
        "perms": "rw-r--r--",
        "size": 651,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "0.4.0-1"
}