{
    "checksum": "6ad22b4f8dcd5e1275c5f75506936052f11e05c4526f8204f4fc57e0c0a13f60",
    "file": "bug-1689424-set-adfspassword-endpointreference-f186d84a54007b09.yaml",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 4,
    "package": "python-keystoneauth1",
    "path": "python-keystoneauth1/4.4.0-2/releasenotes/notes/bug-1689424-set-adfspassword-endpointreference-f186d84a54007b09.yaml",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-keystoneauth1/4.4.0-2/",
        "metric": {
            "size": 2004
        },
        "pts_link": "https://tracker.debian.org/pkg/python-keystoneauth1",
        "sloc": [
            [
                "python",
                17566
            ],
            [
                "xml",
                285
            ],
            [
                "makefile",
                91
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/openstack-team/libs/python-keystoneauth1",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-keystoneauth1/4.4.0-2/releasenotes/notes/bug-1689424-set-adfspassword-endpointreference-f186d84a54007b09.yaml",
    "stat": {
        "perms": "rw-r--r--",
        "size": 500,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "4.4.0-2"
}