{
    "checksum": "4ccdd75faa54f69325846daa714d4295ff64c6d53d5fa00362e25ec5b062c43a",
    "file": "EVCAdmissionFailedCPUVendorUnknown.rst",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 5,
    "package": "python-pyvmomi",
    "path": "python-pyvmomi/6.7.1-3/docs/vim/fault/EVCAdmissionFailedCPUVendorUnknown.rst",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-pyvmomi/6.7.1-3/",
        "metric": {
            "size": 14980
        },
        "pts_link": "https://tracker.debian.org/pkg/python-pyvmomi",
        "sloc": [
            [
                "python",
                9206
            ],
            [
                "xml",
                77
            ],
            [
                "makefile",
                9
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/modules/python-pyvmomi",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-pyvmomi/6.7.1-3/docs/vim/fault/EVCAdmissionFailedCPUVendorUnknown.rst",
    "stat": {
        "perms": "rw-r--r--",
        "size": 347,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "6.7.1-3"
}