{
    "checksum": "cc06a6e1df7e391f12bf13854f57cbe5712c38128c2345b8362d45c31a8cd662",
    "file": "bug-1845322-463ee407b60131c9.yaml",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 2,
    "package": "python-novaclient",
    "path": "python-novaclient/2:17.6.0-2/releasenotes/notes/bug-1845322-463ee407b60131c9.yaml",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-novaclient/2:17.6.0-2/",
        "metric": {
            "size": 2764
        },
        "pts_link": "https://tracker.debian.org/pkg/python-novaclient",
        "sloc": [
            [
                "python",
                24041
            ],
            [
                "makefile",
                22
            ],
            [
                "sh",
                21
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/openstack-team/clients/python-novaclient",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-novaclient/2%3A17.6.0-2/releasenotes/notes/bug-1845322-463ee407b60131c9.yaml",
    "stat": {
        "perms": "rw-r--r--",
        "size": 214,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "2:17.6.0-2"
}