{
    "checksum": "3bd90e690497c9d3f726c1b41314efb14abb8e241f7bb77174959121d2b9fd72",
    "file": "updatezinfo.py",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 1,
    "package": "python-dateutil",
    "path": "python-dateutil/2.8.1-6/updatezinfo.py",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-dateutil/2.8.1-6/",
        "metric": {
            "size": 1500
        },
        "pts_link": "https://tracker.debian.org/pkg/python-dateutil",
        "sloc": [
            [
                "python",
                12688
            ],
            [
                "makefile",
                151
            ],
            [
                "sh",
                70
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/python-team/packages/python-dateutil",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-dateutil/2.8.1-6/updatezinfo.py",
    "stat": {
        "perms": "rw-r--r--",
        "size": 1935,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "2.8.1-6"
}