{
    "checksum": "112875eb7fa2da036d7839739a730bbd1207d554166ac2ca54b79414f613274e",
    "file": "installation.rst",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 1,
    "package": "python-os-faults",
    "path": "python-os-faults/0.2.1-3/doc/source/quickstart/installation.rst",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-os-faults/0.2.1-3/",
        "metric": {
            "size": 668
        },
        "pts_link": "https://tracker.debian.org/pkg/python-os-faults",
        "sloc": [
            [
                "python",
                4680
            ],
            [
                "sh",
                54
            ],
            [
                "makefile",
                24
            ]
        ],
        "suites": [
            "bookworm",
            "bullseye",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/openstack-team/libs/python-os-faults",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-os-faults/0.2.1-3/doc/source/quickstart/installation.rst",
    "stat": {
        "perms": "rw-r--r--",
        "size": 586,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "0.2.1-3"
}