{
    "checksum": "1196d1e62cc9c7c5aefd4c6453bb56c8aa17467bf318b94a234fc94b6f4cc0f5",
    "file": "bug-1924652-2323f905f62ef8ba.yaml",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 1,
    "package": "python-os-brick",
    "path": "python-os-brick/5.0.1-1/releasenotes/notes/bug-1924652-2323f905f62ef8ba.yaml",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-os-brick/5.0.1-1/",
        "metric": {
            "size": 1708
        },
        "pts_link": "https://tracker.debian.org/pkg/python-os-brick",
        "sloc": [
            [
                "python",
                16503
            ],
            [
                "sh",
                39
            ],
            [
                "makefile",
                21
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/openstack-team/libs/python-os-brick",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-os-brick/5.0.1-1/releasenotes/notes/bug-1924652-2323f905f62ef8ba.yaml",
    "stat": {
        "perms": "rw-r--r--",
        "size": 380,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "5.0.1-1"
}