{
    "checksum": "4addf49d759f999f8590bfb839e80fda4508feffabd2b61a77481dbeb7a3dcf9",
    "file": "bug-1561599-d5f541f08ae6274a.yaml",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 4,
    "package": "python-openstackclient",
    "path": "python-openstackclient/5.6.0-2/releasenotes/notes/bug-1561599-d5f541f08ae6274a.yaml",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-openstackclient/5.6.0-2/",
        "metric": {
            "size": 9200
        },
        "pts_link": "https://tracker.debian.org/pkg/python-openstackclient",
        "sloc": [
            [
                "python",
                106451
            ],
            [
                "makefile",
                137
            ],
            [
                "sh",
                29
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/openstack-team/clients/python-openstackclient",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-openstackclient/5.6.0-2/releasenotes/notes/bug-1561599-d5f541f08ae6274a.yaml",
    "stat": {
        "perms": "rw-r--r--",
        "size": 349,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "5.6.0-2"
}