{
    "checksum": "811a35091ac72f7ca436f3b9a3fe7cf70bd08d5e660f8848a03c5d5f6a0f6b6b",
    "file": "log-request-id-e7f67a23a0ed5c7b.yaml",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/plain"
    },
    "number_of_duplicates": 4,
    "package": "python-glanceclient",
    "path": "python-glanceclient/1:3.5.0-2/releasenotes/notes/log-request-id-e7f67a23a0ed5c7b.yaml",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-glanceclient/1:3.5.0-2/",
        "metric": {
            "size": 1512
        },
        "pts_link": "https://tracker.debian.org/pkg/python-glanceclient",
        "sloc": [
            [
                "python",
                15487
            ],
            [
                "sh",
                90
            ],
            [
                "makefile",
                27
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/openstack-team/clients/python-glanceclient",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-glanceclient/1%3A3.5.0-2/releasenotes/notes/log-request-id-e7f67a23a0ed5c7b.yaml",
    "stat": {
        "perms": "rw-r--r--",
        "size": 201,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "1:3.5.0-2"
}