{
    "checksum": "1b3d5c4460b07da33b65eed6010e3bd39e9a8478b8df056e15ecd5b29ef04b11",
    "file": "error_code_list2.rst",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/x-python"
    },
    "number_of_duplicates": 1,
    "package": "mypy",
    "path": "mypy/0.910-4/docs/source/error_code_list2.rst",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/mypy/0.910-4/",
        "metric": {
            "size": 15956
        },
        "pts_link": "https://tracker.debian.org/pkg/mypy",
        "sloc": [
            [
                "python",
                76299
            ],
            [
                "cpp",
                11212
            ],
            [
                "ansic",
                3653
            ],
            [
                "makefile",
                241
            ],
            [
                "sh",
                15
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/med-team/mypy",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/m/mypy/0.910-4/docs/source/error_code_list2.rst",
    "stat": {
        "perms": "rw-r--r--",
        "size": 7058,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "0.910-4"
}