{
    "checksum": "53509497b8607e6e90e40690e57295b81721b551bc8f1dc9118750b5dd273dcd",
    "file": "test_NoteGet_invalid_xml.xml",
    "mime": {
        "encoding": "us-ascii",
        "type": "text/xml"
    },
    "number_of_duplicates": 3,
    "package": "python-osmapi",
    "path": "python-osmapi/2.0.2+ds-1/tests/fixtures/test_NoteGet_invalid_xml.xml",
    "pkg_infos": {
        "area": "main",
        "copyright": true,
        "ctags_count": 0,
        "license": "/copyright/license/python-osmapi/2.0.2+ds-1/",
        "metric": {
            "size": 708
        },
        "pts_link": "https://tracker.debian.org/pkg/python-osmapi",
        "sloc": [
            [
                "python",
                3144
            ],
            [
                "xml",
                1583
            ],
            [
                "makefile",
                41
            ],
            [
                "sh",
                16
            ]
        ],
        "suites": [
            "bookworm",
            "sid"
        ],
        "vcs_browser": "https://salsa.debian.org/debian-gis-team/python-osmapi",
        "vcs_type": "git"
    },
    "raw_url": "/data/main/p/python-osmapi/2.0.2%2Bds-1/tests/fixtures/test_NoteGet_invalid_xml.xml",
    "stat": {
        "perms": "rw-r--r--",
        "size": 468,
        "symlink_dest": null,
        "type": "-"
    },
    "text_file": true,
    "type": "file",
    "version": "2.0.2+ds-1"
}